// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwtqeukqejnpcbdufonl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3dHFldWtxZWpucGNiZHVmb25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODY2MjcsImV4cCI6MjA1ODU2MjYyN30.Fkz-92PiDgCTjJu1VUHHQmh1e_yKPEeph84rkHwdlL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);